### ISSUE TITLE
Generated constructor should be inserted at cursor's location

### ISSUE THREAD

**Issue by alexcom** [jkovacs/CopyConstructorPlugin#2]
For some reason plugin is generating new constructor somewhere in the middle of the file.
I would expect it to insert new constructor at cursor location.

**Comment by jkovacs** [comment]
@alexcom thanks for reporting this, I just submitted the update to Jetbrains. Please check in the next couple of days for an update of the plugin and see if it works for you.

**Comment by alexcom** [comment]
Sorry for the delay. Works as I expected now. Thank you!
